linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  gocyclo:
    min-complexity: 10
    max-complexity: 12
  dupl:
    threshold: 500
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/reportportal/service-index
  gci:
    local-prefixes: github.com/reportportal/service-index
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting
      - yodaStyleExpr
      - unnamedResult
      - commentedOutCode
      - assignOp
      - docStub

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - performance
    - unused
  disable:
    - godot
    - gocritic
    - funlen
run:
  # default concurrency is a available CPU number
  concurrency: 1
#  skip-dirs:
#    - test/testdata_etc

