version: "2"
run:
  concurrency: 1
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - gocyclo
    - godox
    - gomodguard
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unparam
    - wrapcheck
    - zerologlint
  disable:
    - funlen
    - gocritic
    - godot
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: 'replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil'
    dupl:
      threshold: 500
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - wrapperFunc
        - commentFormatting
        - yodaStyleExpr
        - unnamedResult
        - commentedOutCode
        - assignOp
        - docStub
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/reportportal/service-index)
    goimports:
      local-prefixes:
        - github.com/reportportal/service-index
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
