FROM golang:1.13.7-alpine

RUN apk --no-cache add build-base git

WORKDIR /go/src/github.com/reportportal/service-index/
ARG version

ENV GO111MODULE=on

## Copy makefile and glide before to be able to cache vendor
COPY Makefile ./

ENV VERSION=$version

COPY ./ ./
RUN make build v=${VERSION}

FROM alpine:latest
ARG service
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/reportportal/service-index/bin/service-index ./app
EXPOSE 8080
CMD ["./app"]
