FROM golang:1.15.7-alpine

RUN apk --no-cache add build-base git

WORKDIR /go/src/github.com/reportportal/service-index/

ENV GO111MODULE=on

## Copy makefile and glide before to be able to cache vendor
COPY Makefile go.mod go.sum ./
RUN make get-build-deps

ARG version
ENV VERSION=$version

COPY ./ ./
RUN make build v=${VERSION}

FROM alpine:latest
ARG service
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/reportportal/service-index/bin/service-index ./app
EXPOSE 8080
CMD ["./app"]
