version: "3.8"
services:

  ## External dependencies

  gateway:
    image: traefik:v2.11.31
    container_name: traefik
    logging: &logging
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"
    ports:
      - "8080:8080" # ReportPortal UI
      - "8081:8081" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker=true
      - --providers.docker.constraints=Label(`traefik.expose`, `true`)
      - --entrypoints.web.address=:8080
      - --entrypoints.traefik.address=:8081
      - --api.dashboard=true
      - --api.insecure=true
    networks:
      - reportportal
    restart: always

  index:
    build: .
    container_name: reportportal-index
    logging:
      <<: *logging
    depends_on:
      gateway:
        condition: service_started
    environment:
      LB_URL: http://gateway:8081
      TRAEFIK_V2_MODE: 'true'
    healthcheck:
      test: wget -q --spider http://0.0.0.0:8080/health
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.http.routers.index.rule=PathPrefix(`/`)"
      - "traefik.http.routers.index.service=index"
      - "traefik.http.services.index.loadbalancer.server.port=8080"
      - "traefik.http.services.index.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
    networks:
      - reportportal
    restart: always

  ui:
    image: reportportal/service-ui:5.14.6
    container_name: reportportal-ui
    environment:
      RP_SERVER_PORT: "8080"
    healthcheck:
      test: wget -q --spider http://0.0.0.0:8080/health
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.http.middlewares.ui-strip-prefix.stripprefix.prefixes=/ui"
      - "traefik.http.routers.ui.middlewares=ui-strip-prefix@docker"
      - "traefik.http.routers.ui.rule=PathPrefix(`/ui`)"
      - "traefik.http.routers.ui.service=ui"
      - "traefik.http.services.ui.loadbalancer.server.port=8080"
      - "traefik.http.services.ui.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
    networks:
      - reportportal
    restart: always

volumes:
  opensearch:
  storage:
  postgres:

networks:
  reportportal: