FROM golang:1.11.1-alpine

WORKDIR /go/src/github.com/reportportal/service-index/
ARG version

## Copy makefile and glide before to be able to cache vendor
COPY Makefile ./
RUN make get-build-deps

COPY glide.yaml ./
COPY glide.lock ./

RUN make vendor

ENV VERSION=$version

RUN make get-build-deps
COPY ./ ./
RUN make build v=${VERSION}

FROM alpine:latest
ARG service
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/reportportal/service-index/bin/service-index ./app
EXPOSE 8080
CMD ["./app"]
