name: Build

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - readme.md
      - README.md
      - CHANGELOG.md

  pull_request:
    branches:
      - master
      - develop

env:
  UI_BUILD_REACT: 'app/'
  GODIRS_NOVENDOR: '`go list ./... | grep -v /vendor/`'
  PACKAGE_COMMONS: 'github.com/reportportal/commons-go/v5'
  BINARY_DIR: 'bin'
  BUILD_INFO_LDFLAGS: >-
    -ldflags "-extldflags '"-static"'
    -X ${PACKAGE_COMMONS}/commons.repo=${GITHUB_REPOSITORY}
    -X ${PACKAGE_COMMONS}/commons.branch=${GITHUB_SHA}
    -X ${PACKAGE_COMMONS}/commons.buildDate=${BUILD_DATE}
    -X ${PACKAGE_COMMONS}/commons.version=${VERSION}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Date
        id: date
        run: 'echo "BUILD_DATE=`date +%FT%T%z`" >> $GITHUB_ENV'

      - uses: actions/checkout@v2
        id: checkout

      - name: Setup Go
        id: setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.7'

      - name: Go Dependencies
        id: dependencies
        run: 'go mod download'

      - name: Go Linter
        id: linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36.0
          skip-go-installation: true
          args: '--deadline 10m'

      - name: Go Tests
        id: tests
        run: 'go test ${{ env.GODIRS_NOVENDOR }}'

      - name: Go Build
        id: build
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: 'go build ${{ env.BUILD_INFO_LDFLAGS }} -o ${{ env.BINARY_DIR }}/service-index ./'
