name: Build develop Docker image

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
      - README.md

jobs:
  variables-setup:
    name: Setting variables for docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create variables
        id: vars
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      date: ${{ steps.vars.outputs.date }}
      sha_short: ${{ steps.vars.outputs.sha_short }}

  call-docker-build:
    name: Call develop Docker build
    needs: variables-setup
    uses: reportportal/.github/.github/workflows/build-docker-image.yaml@main
    with:
      image-tag: 'develop-${{ github.run_number }}'
      version: '${{ github.ref_name }}-${{ needs.variables-setup.outputs.sha_short }}'
      date: ${{ needs.variables-setup.outputs.date }}
    secrets: inherit
