name: Release Workflow

on:
  release:
    types: [published]

jobs:
  publish-artifacts:
    uses: reportportal/.github/.github/workflows/go-build-release.yaml@main
    with:
      release_version: ${{ github.event.release.tag_name }}
      repository_url: 'https://repo1.maven.org/maven2/com/epam/reportportal'
      branch: master
      service_name: service/index